<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Karl Gregory">

<title>Monte Carlo experiments – Computing in Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./R_importdata.html" rel="next">
<link href="./R_MCmethods.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./R_running.html">R</a></li><li class="breadcrumb-item"><a href="./R_MCexperiments.html">Monte Carlo experiments</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Computing in Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./R_running.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Types of objects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_basicops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic operations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_functiondef.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Defining functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_forloop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">For loops</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_whileloop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">While loops</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_statfunctions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_MCmethods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Monte Carlo methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_MCexperiments.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Monte Carlo experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_importdata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Importing and formatting data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_manipulatedata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Merging, stacking, reshaping, and aggregating data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Python</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Homework</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_hw_tablesmake.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Make these tables in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_hw_gltmpplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Make this plot in R</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#approximating-an-expected-value" id="toc-approximating-an-expected-value" class="nav-link active" data-scroll-target="#approximating-an-expected-value">Approximating an expected value</a>
  <ul class="collapse">
  <li><a href="#normal-example" id="toc-normal-example" class="nav-link" data-scroll-target="#normal-example">Normal example</a></li>
  <li><a href="#bernoulli-examples" id="toc-bernoulli-examples" class="nav-link" data-scroll-target="#bernoulli-examples">Bernoulli examples</a></li>
  </ul></li>
  <li><a href="#coverage-probability-of-a-confidence-interval" id="toc-coverage-probability-of-a-confidence-interval" class="nav-link" data-scroll-target="#coverage-probability-of-a-confidence-interval">Coverage probability of a confidence interval</a></li>
  <li><a href="#type-i-error-rate-of-a-test" id="toc-type-i-error-rate-of-a-test" class="nav-link" data-scroll-target="#type-i-error-rate-of-a-test">Type I error rate of a test</a></li>
  <li><a href="#practice" id="toc-practice" class="nav-link" data-scroll-target="#practice">Practice</a>
  <ul class="collapse">
  <li><a href="#write-code" id="toc-write-code" class="nav-link" data-scroll-target="#write-code">Write code</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./R_running.html">R</a></li><li class="breadcrumb-item"><a href="./R_MCexperiments.html">Monte Carlo experiments</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Monte Carlo experiments</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Karl Gregory </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="hidden">
<p>$$</p>
<p>$$</p>
</div>
<p>Statisticians have special uses for the Monte Carlo methods introduced in the previous note. Very often statisticians run computer experiments to check how well a statistical method performs. This is particularly important when a statistical method, say a test of hypotheses or the construction of a confidence interval, depends on asymptotic results established under the assumption that the sample size <span class="math inline">\(n\)</span> approaches infinity. You may recall the central limit theorem, which tells us that a sample mean, centered and then divided by its standard deviation, will have a distribution approaching the standard normal distribution as the sample size is increased to infinity. It is upon such results that so many statistical methods are based; but in practice, it is impossible to observe an infinite sample size. It therefore becomes important to know how large a sample size is large enough for asymptotic distribution theory to “kick in” and ensure that our methods have the advertized properties—Type I error rates of tests and coverage probabilities for confidence intervals, for example.</p>
<p>These computer experiments are essentially Monte Carlo approximations to integrals, not so different from those we studied in the previous note.</p>
<section id="approximating-an-expected-value" class="level2">
<h2 class="anchored" data-anchor-id="approximating-an-expected-value">Approximating an expected value</h2>
<p>The Monte Carlo method for approximating an integral can be used to approximation an <em>expected value</em>, which is useful when this is difficult to compute exactly. Recall that for a random variable <span class="math inline">\(X\)</span>, the expected value, denoted <span class="math inline">\(\mathbb{E}X\)</span> represents the central value of the distribution of <span class="math inline">\(X\)</span> in the sense that if one were to observe many realizations of <span class="math inline">\(X\)</span> and average them, this average should be close to <span class="math inline">\(\mathbb{E}X\)</span>. So we think of <span class="math inline">\(\mathbb{E}X\)</span> as the theoretical <em>mean</em> of <span class="math inline">\(X\)</span>, that is the mean we would obtain if we could observe <span class="math inline">\(X\)</span> an infinite number of times.</p>
<p>For example, if <span class="math inline">\(X \sim \text{Normal}(\mu,\sigma^2)\)</span> for some <span class="math inline">\(\mu \in \mathbb{R}\)</span> and <span class="math inline">\(\sigma^2 &gt;0\)</span>, then <span class="math inline">\(\mathbb{E}X = \mu\)</span>. For another example, if <span class="math inline">\(X \sim \text{Binomial}(n,p)\)</span> for some number of Bernoulli trials <span class="math inline">\(n \geq 1\)</span> and some success probability <span class="math inline">\(p \in (0,1)\)</span>, then <span class="math inline">\(\mathbb{E}X = np\)</span>.</p>
<p>In these two examples, formulas are available for obtaining <span class="math inline">\(\mathbb{E}X\)</span>, but this may not always be the case, especially if one is interested in the expected value of some transformed version of <span class="math inline">\(X\)</span>, say <span class="math inline">\(g(X)\)</span>. It may be quite difficult to obtain a formula giving an expression for <span class="math inline">\(\mathbb{E}g(X)\)</span>, depending on the particular function <span class="math inline">\(g\)</span>. For example, if <span class="math inline">\(X \sim \text{Normal}(\mu,\sigma^2)\)</span>, there are no no simple formulas giving <span class="math inline">\(\mathbb{E}\sin(X)\)</span> or <span class="math inline">\(\mathbb{E}\sqrt{|X|}\)</span>. In such cases, it may be sufficient to obtain a Monte Carlo approximation to the expected value as an alternative to working out how to compute the exact value.</p>
<p>Here is how Monte Carlo simulation works: It is based on a result in probability theory called the Strong Law of Large Numbers, which says that as you draw a larger and larger number of realizations of a random variable, the average of these realizations will approach the expected value of the random variable. To leverage this result, the Monte Carlo strategy for constructing an approximation to the expected value of a random variable <span class="math inline">\(X\)</span> is to generate a large number <span class="math inline">\(N\)</span> of realization of <span class="math inline">\(X\)</span>, say <span class="math inline">\(X_1,\dots,X_N\)</span> and then use the average <span class="math inline">\(N^{-1}\sum_{i=1}^NX_i\)</span> as an approximation to <span class="math inline">\(\mathbb{E}X\)</span>. Similarly, to obtain an approximation to <span class="math inline">\(\mathbb{E}g(X)\)</span>, where <span class="math inline">\(g\)</span> is some function transforming the values of <span class="math inline">\(X\)</span>, one uses the average <span class="math inline">\(N^{-1}\sum_{i=1}^Ng(X_i)\)</span>.</p>
<section id="normal-example" class="level3">
<h3 class="anchored" data-anchor-id="normal-example">Normal example</h3>
<p>Suppose we want to find <span class="math inline">\(\mathbb{E}\sqrt{|X|}\)</span>, where <span class="math inline">\(X \sim \text{Normal}(0,1)\)</span>. The code below runs a Monte Carlo simulation to obtain an approximation to <span class="math inline">\(\mathbb{E}\sqrt{|X|}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N) <span class="co"># mu = 0 and sd = 1 by default</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>gX <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(X))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mgX <span class="ot">&lt;-</span> <span class="fu">mean</span>(gX)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>mgX</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8213095</code></pre>
</div>
</div>
<p>Try running this several times with smaller and larger choice of <span class="math inline">\(N\)</span>. You’ll notice that the result becomes more stable for larger values of <span class="math inline">\(N\)</span>.</p>
<p>It is sometimes interesting, having generated <span class="math inline">\(X_1,\dots,X_N\)</span>, to make a plot of the sequence of Monte Carlo approximations <span class="math display">\[
\frac{1}{i}(g(X_1) + \dots + g(X_i)), \quad i = 1,\dots, N.
\]</span> We can see in the plot below that the approximation in the beginning (when we are averaging just a very small number of realizations) is very erratic and unreliable. However, the approximation becomes more stable as we include more realizations. The code below uses the <code>cumsum()</code> function, which takes a cumulative sum of a numeric vector. Run <code>?cumsum()</code> to learn how it works.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mgX_seq <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(gX)<span class="sc">/</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mgX_seq,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type=</span><span class="st">"l"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Monte Carlo approximation"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"N"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> mgX,<span class="at">lty =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_MCexperiments_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bernoulli-examples" class="level3">
<h3 class="anchored" data-anchor-id="bernoulli-examples">Bernoulli examples</h3>
<p>We quite often use Monte Carlo simulation when our random variable <span class="math inline">\(X\)</span> is a Bernoulli random variable with an unknown success probability <span class="math inline">\(p\)</span>. Recalling how to compute the expected value for discrete random variables, we see that for <span class="math inline">\(X \sim \text{Bernoulli}(p)\)</span>, we have <span class="math display">\[
\mathbb{E}X = 1 \cdot \mathbb{P}(X = 1) + 0 \cdot \mathbb{P}(X = 0) = p,
\]</span> so the expected value <span class="math inline">\(\mathbb{E}X\)</span> is the same as the probability <span class="math inline">\(\mathbb{P}(X = 1) = p\)</span>.</p>
<p>But in what kind of situation will we <em>not know</em> the success probability <span class="math inline">\(p\)</span>? We will come to such a case in a moment, but first, as an exercise, let’s see how a Monte Carlo simulation would look for approximating the expected value, i.e.&nbsp;the success probability of a Bernoulli random variable when this is known:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.2</span> <span class="co"># suppose this is the value of p, but that it is unknown to us</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(N,<span class="dv">1</span>,p)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>mX <span class="ot">&lt;-</span> <span class="fu">mean</span>(X)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>mX</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2032</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a plot</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mX_seq <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(X)<span class="sc">/</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mX_seq,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">type=</span><span class="st">"l"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Monte Carlo approximation"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"N"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> p,<span class="at">lty =</span> <span class="dv">3</span>) <span class="co"># horizontal line at the true p</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_MCexperiments_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We notice, as we did in the first example, that the Monte Carlo approximation improves as the number of realizations on which it is based increases.</p>
<p>Now, how about a setting in which the true success probability <span class="math inline">\(p\)</span> is unknown to us? A very common application of Monte Carlo simulation is to evaluate the performance of confidence intervals or statistical tests advertised to guarantee a certain coverage probability or type I error rate. One can construct the confidence interval or run the test on a large number of simulated data sets in order to obtain a Monte Carlo approximation to the probability that the confidence interval will cover its target or that the test will reject its null hypothesis.</p>
</section>
</section>
<section id="coverage-probability-of-a-confidence-interval" class="level2">
<h2 class="anchored" data-anchor-id="coverage-probability-of-a-confidence-interval">Coverage probability of a confidence interval</h2>
<p>First consider assessing the coverage performance of a confidence interval. Suppose one is to observe a random sample <span class="math inline">\(Y_1,\dots,Y_n\)</span> from some distribution having unknown mean <span class="math inline">\(\mu\)</span> and some finite variance, and one decides to construct a confidence interval for <span class="math inline">\(\mu\)</span> as <span class="math display">\[
\bar Y_n \pm t_{n-1,\alpha/2}\frac{S_n}{\sqrt{n}},
\]</span> where <span class="math inline">\(\bar Y_n = n^{-1}(Y_1+\dots+Y_n)\)</span>, <span class="math inline">\(S_n^2 = (n-1)^{-1}\sum_{i=1}^n(Y_i - \bar Y_n)^2\)</span>, and <span class="math inline">\(t_{n-1,\alpha/2}\)</span> is the upper <span class="math inline">\(\alpha/2\)</span> quantile of the <span class="math inline">\(t\)</span> distribution with degrees of freedom <span class="math inline">\(n-1\)</span>, where <span class="math inline">\(\alpha \in (0,1)\)</span>. This is the classical “<span class="math inline">\(t\)</span>-interval”, and it is guaranteed to capture the true mean with probability exactly <span class="math inline">\(1-\alpha\)</span> provided <span class="math inline">\(Y_1,\dots,Y_n\)</span> is a random sample from a population with a Normal distribution. However, if the population distribution is not Normal, this interval will not have exactly the advertised coverage probability of <span class="math inline">\(1-\alpha\)</span> (though one expects that its coverage probability will approach <span class="math inline">\(1-\alpha\)</span> as <span class="math inline">\(n\)</span> increases, because of the central limit theorem). To get an approximation to the probability with which this interval will cover its target when the population distribution is <em>not</em> normal, one can run a Monte Carlo simulation. Indeed, it is quite difficult to investigate the performance of this interval in any other way when the population is non-normal!</p>
<p>Here is how we can think about it: Let <span class="math inline">\(X\)</span> be a variable taking the value <span class="math inline">\(1\)</span> if the confidence interval covers its target and taking the value zero if the interval misses. Then <span class="math inline">\(X\)</span> is a Bernoulli random variable with unknown success probability <span class="math inline">\(p\)</span>. Equipped with the knowledge of the for loop, we can run a Monte Carlo simulation to obtain an approximation to the coverage probability of the interval when the sample <span class="math inline">\(Y_1,\dots,Y_n\)</span> is drawn from some distribution other than a Normal distribution—and for any sample size <span class="math inline">\(n\)</span>.</p>
<p>Let’s suppose <span class="math inline">\(Y_1,\dots,Y_n\)</span> are drawn from the <span class="math inline">\(\text{Exponential}(\lambda)\)</span> distribution, so that <span class="math inline">\(\mathbb{E}Y = 1/\lambda\)</span> (see my STAT 515 lecture on this <a href="https://people.stat.sc.edu/gregorkb/STAT_515_fa_2023/STAT_515_Lec_08_slides_annotated.pdf">here</a>). Here we go:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span>                          <span class="co"># set the sample size n</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>                    <span class="co"># use parameterization of exponential such that it has expected value 1/lambda</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>lambda                   <span class="co"># the population mean targeted by the confidence interval</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span>                    <span class="co"># set alpha to 0.05 to get a 95% confidence interval</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>t_val <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>)     <span class="co"># retrieve the t-quantile</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">5000</span>                        <span class="co"># set the number of Monte Carlo realizations to generate</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)                  <span class="co"># create an empty vector to populate with 0 or 1</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N){</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  Y <span class="ot">&lt;-</span> <span class="fu">rexp</span>(n,lambda)            <span class="co"># draw sample of size n from exponential distribution</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  Ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(Y)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  Sn <span class="ot">&lt;-</span> <span class="fu">sd</span>(Y)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  lo <span class="ot">&lt;-</span> Ybar <span class="sc">-</span> t_val <span class="sc">*</span> Sn <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  up <span class="ot">&lt;-</span> Ybar <span class="sc">+</span> t_val <span class="sc">*</span> Sn <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  X[i] <span class="ot">&lt;-</span> (lo <span class="sc">&lt;</span> mu) <span class="sc">&amp;</span> (up <span class="sc">&gt;</span> mu)  <span class="co"># check if confidence interval contains mu</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9028</code></pre>
</div>
</div>
<p>In the Monte Carlo simulation, the confidence interval <span class="math inline">\(\bar Y_n \pm t_{n-1,\alpha/2}S_n/\sqrt{n}\)</span> contained the true mean <span class="math inline">\(90.28\%\)</span> of the time.</p>
</section>
<section id="type-i-error-rate-of-a-test" class="level2">
<h2 class="anchored" data-anchor-id="type-i-error-rate-of-a-test">Type I error rate of a test</h2>
<p>Now let’s consider using Monte Carlo simulation to obtain the Type I error rate of a statistical test when the assumptions required for the test do not hold. Recall that the Type I error rate of a test is the probability that it rejects the null hypothesis when this is true. As an example of a test, let’s use the <span class="math inline">\(F\)</span> test for equality of means in a one-way ANOVA experiment (for a refresher on this, see my STAT 515 notes <a href="https://people.stat.sc.edu/gregorkb/STAT_515_fa_2023/STAT_515_Lec_17_slides_annotated.pdf">here</a>). Suppose we have <span class="math inline">\(K\)</span> treatment groups with <span class="math inline">\(n\)</span> subjects per treatment group and let <span class="math inline">\(Y_{ij}\)</span> denote the response observed on subject <span class="math inline">\(j\)</span> of treatment group <span class="math inline">\(i\)</span>. One typically assumes the model <span class="math display">\[
Y_{ij} = \mu_i + \varepsilon_{ij}, \quad i = 1,\dots,K, \quad j = 1,\dots,n,
\]</span> where the <span class="math inline">\(\mu_i\)</span> are treatment group means and the <span class="math inline">\(\varepsilon_{ij}\)</span> are independent error terms with the <span class="math inline">\(\text{Normal}(0,\sigma^2)\)</span> distribution for some unknown <span class="math inline">\(\sigma^2 &gt; 0\)</span>. The <span class="math inline">\(F\)</span> test rejects the equal-means hypothesis <span class="math display">\[
H_0\text{:} ~ \mu_1 = \dots = \mu_K
\]</span> at significance level <span class="math inline">\(\alpha \in (0,1)\)</span> if <span class="math display">\[
F  = \frac{\operatorname{MS}_{\operatorname{Treatment}}}{\operatorname{MS}_{\operatorname{Error}}} &gt; F_{K-1,K(n-1),\alpha},
\]</span> where <span class="math inline">\(F_{K-1,K(n-1),\alpha}\)</span> is the upper <span class="math inline">\(\alpha\)</span> quantile of the <span class="math inline">\(F\)</span> distribution with numerator degrees of freedom <span class="math inline">\(K-1\)</span> and denominator degrees of freedom <span class="math inline">\(K(n-1)\)</span>.</p>
<p>Now, the above test is calibrated such that when <span class="math inline">\(H_0\)</span> is true, it will still reject this hypothesis with probability <span class="math inline">\(\alpha\)</span>. However, the calibration of the test depends on the assumption that the responses <span class="math inline">\(Y_{ij}\)</span> are normally distribution around the treatment group means. If this is not the case, there is no guarantee that the test will maintain the its advertised Type I error rate.</p>
<p>Below is a Monte Carlo simulation designed to obtain an approximation to the Type I error rate of the one-way ANOVA F-test when the error terms <span class="math inline">\(\varepsilon_{ij}\)</span> do not have the normal distribution but rather a skewed distribution, namely the chi-squared distribution with degree of freedom 1, centered by subtracting 1 (if <span class="math inline">\(\varepsilon \sim \chi^2_1\)</span> then <span class="math inline">\(\mathbb{E}\varepsilon = 1\)</span>). The code makes use of the Kronecker product operator <code>%x%</code> for setting up the treatment vector and the <code>lm()</code> function for computing the F statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">3</span>                                        <span class="co"># set number of treatment groups </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">3</span>                                        <span class="co"># set number of subjects in each group</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>trt <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>K) <span class="sc">%x%</span> <span class="fu">rep</span>(<span class="dv">1</span>,n))         <span class="co"># construct trt column as a factor. Use kronecker product %x%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">5000</span>                                     <span class="co"># set number of Monte Carlo draws</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)                               <span class="co"># create empty vector to populate with Bernoulli realizations</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N){</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  e <span class="ot">&lt;-</span> <span class="fu">rchisq</span>(n<span class="sc">*</span>K,<span class="at">df=</span><span class="dv">1</span>)<span class="sc">-</span><span class="dv">1</span>                     <span class="co"># generate error terms from a chi-square 1 distribution (which is skewed) centered to have mean zero</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  Y <span class="ot">&lt;-</span> e                                      <span class="co"># draw Y such that the trt groups have all the same mean, so the null hypothesis will be true</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  lm_out <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y<span class="sc">~</span>trt)                         <span class="co"># use lm() function to run F test</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  sum_lm_out <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_out)               <span class="co"># dig out the F statistic</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  Fstat <span class="ot">&lt;-</span> sum_lm_out<span class="sc">$</span>fstatistic[<span class="dv">1</span>]           </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  pval <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(Fstat,K<span class="dv">-1</span>,K<span class="sc">*</span>(n<span class="dv">-1</span>))           <span class="co"># compute the p-value</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  X[i] <span class="ot">&lt;-</span> pval <span class="sc">&lt;</span> alpha                        <span class="co"># reject the null hypothesis if the p-value is less than alpha</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(X)                                       <span class="co"># the Type I error rate</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0364</code></pre>
</div>
</div>
<p>The Monte Carlo simulation approximated the Type I error rate of the test in this setup as 0.0364, somewhat lower than the nominal 0.05. We refer to 0.05 as the “nominal” size, because this is the advertised or “named” size of the test, whereas the test <em>actually</em> performs with a lower Type I error rate (not necessarily a good thing, because of the power/size trade-off), suggesting that the test is unduly conservative (overly reluctant to reject) in this setup.</p>
</section>
<section id="practice" class="level2">
<h2 class="anchored" data-anchor-id="practice">Practice</h2>
<p>Practice writing code and anticipating the output of code with the following exercises.</p>
<section id="write-code" class="level3">
<h3 class="anchored" data-anchor-id="write-code">Write code</h3>
<ol type="1">
<li>Write a function which computes the test statistic and returns the p-value of Pearson’s chi-squared test of no association between two categorical variables having <span class="math inline">\(J\)</span> and <span class="math inline">\(K\)</span> levels, respectively. That is, given a table of observed counts <span class="math display">\[
\quad \begin{array}{c|cccc}
      &amp; 1 &amp; 2 &amp; \dots  &amp; K &amp; \\\hline
1 &amp; O_{11} &amp; O_{12}&amp; \dots &amp; O_{1K} &amp; \\
2 &amp; O_{21} &amp; O_{22}&amp; \dots &amp; O_{2K} \\
\vdots &amp;\vdots&amp;\vdots&amp;\ddots&amp;\vdots\\
J &amp; O_{J1} &amp; O_{J2}&amp; \dots &amp; O_{JK}
\end{array}
\]</span> and letting <span class="math inline">\(O_{j.}\)</span> denote the sum of the counts in row <span class="math inline">\(j\)</span>, <span class="math inline">\(O_{.k}\)</span> the sum of the counts in column <span class="math inline">\(k\)</span>, and <span class="math inline">\(O_{..}\)</span> the sum of all the observed counts, write a function to compute <span class="math display">\[
W = \sum_{j=1}^J\sum_{k=1}^K (O_{jk} - E_{jk})^2/E_{jk},
\]</span> where <span class="math inline">\(E_{jk} = O_{j.}O_{.k}/O_{..}\)</span>. The p-value of the test statistic is given as the probability that a random variable having the <span class="math inline">\(\chi^2_{(J-1)(K-1)}\)</span> distribution exceeds the observed value of <span class="math inline">\(W\)</span>.</li>
</ol>
<ol start="2" type="1">
<li>We can generate a table of observed values under the null hypothesis of no association with the code below. Use this code as a starting point to write a simulation which generates <span class="math inline">\(1000\)</span> such tables of observed counts and on each one of them carries out the test of no association as some significance level <span class="math inline">\(\alpha\)</span> of your own choosing (you may use your function from 1. or you may use the <code>chisq.test()</code> function to carry out the test). Record on what proportion of times out of the <span class="math inline">\(1000\)</span> the null hypothesis is rejection; this is the Type I error rate.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>J <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="co"># number of rows</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="co"># number of columns</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="co"># number of subjects</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>U <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>J,N,<span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.2</span>,<span class="fl">0.4</span>,<span class="fl">0.4</span>),<span class="at">replace =</span> T)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>V <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>K,N,<span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.4</span>,<span class="fl">0.1</span>,<span class="fl">0.2</span>,<span class="fl">0.3</span>),<span class="at">replace =</span> T)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>O <span class="ot">&lt;-</span> <span class="fu">table</span>(U,V)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>O</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   V
U    1  2  3  4
  1 37 14 30 24
  2 72 22 28 67
  3 86 22 34 64</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>The code below generates fake simple linear regression data according to the model <span class="math display">\[
Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i, \quad i = 1,\dots,n,
\]</span> where the error terms <span class="math inline">\(\varepsilon_i\)</span>, instead of having a normal distribution as is commonly assumed, have a skewed distribution—in particular a chi-squared distribution shifted so as to have zero mean and scaled so as to have unit variance. The code then uses the <code>lm()</code> function to obtain a table of coefficient estimates which includes the p-value for testing <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = 0\)</span> versus <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\beta_1 \neq 0\)</span>. Note that the non-normality of the error terms shows up in the normal Q-Q plot to a degree that we might say we cannot trust an analysis based on the assumption of normal error terms. However, asymptotic theory suggests that even when the error terms are not normally distributed, the least-squares regression coefficient estimators should still have approximately normal distributions if the sample size is large. To investigate this, run a simulation, generating many data sets (say 1000) exactly as below and obtain for each data set the p-value for testing whether the coefficient <span class="math inline">\(\beta_1\)</span> is nonzero. Then record on what proportion of data sets the <span class="math inline">\(p\)</span>-value fell below <span class="math inline">\(0.05\)</span>. Note that in the code below the true value of <span class="math inline">\(\beta_1\)</span> is set to zero, so that the null hypothesis is true. The result of the simulation will therefore be an approximation to the actual Type I error rate of the test (remember that we reject <span class="math inline">\(H_0\)</span> when the p-value is less than our significance level <span class="math inline">\(\alpha\)</span>, and the Type I error rate is the probability of falsely rejecting <span class="math inline">\(H_0\)</span>). This simulation will tell us whether the non-normality of the error term distribution will cause our inferences to be invalid.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="dv">0</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(n,<span class="dv">0</span>,<span class="dv">5</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> (<span class="fu">rchisq</span>(n,df) <span class="sc">-</span> df)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">2</span><span class="sc">*</span>df) <span class="co"># scale to have zero mean and unit variance</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>x <span class="sc">+</span> e</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(out,<span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_MCexperiments_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>summ_lm <span class="ot">&lt;-</span> <span class="fu">summary</span>(out)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>summ_lm<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value   Pr(&gt;|t|)
(Intercept) 0.82787968  0.4465373 1.8539989 0.08020037
x           0.07756801  0.1621308 0.4784285 0.63810479</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./R_MCmethods.html" class="pagination-link" aria-label="Monte Carlo methods">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Monte Carlo methods</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./R_importdata.html" class="pagination-link" aria-label="Importing and formatting data">
        <span class="nav-page-text">Importing and formatting data</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>